spring:
  dataSource:
    username: root
    password: sujung9300
    url: jdbc:mysql://localhost:3306/constar
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

